name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: storemesh-bff
      - uses: actions/checkout@v4
        with:
          repository: sartim/storemesh-order-service
          path: storemesh-order-service
      - uses: actions/checkout@v4
        with:
          repository: sartim/storemesh-product-service
          path: storemesh-product-service
      - uses: actions/checkout@v4
        with:
          repository: sartim/storemesh-inventory-service
          path: storemesh-inventory-service
      - uses: actions/checkout@v4
        with:
          repository: sartim/storemesh-user-service
          path: storemesh-user-service
      - uses: actions/setup-go@v5
        with:
          go-version-file: storemesh-bff/go.mod
          cache: true
      - run: go test ./...
        working-directory: storemesh-bff
